export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_ERRORS = "GET_ERRORS";
export const GET_USER = "GET_USER";
export const GET_CURRENT_USER = "GET_USER";
export const USER_LOG_IN_SUCCESS ="USER_LOG_IN_SUCCESS";
export const USER_LOG_IN_FAILURE = "USER_LOG_IN_FAILURE";
export const USER_LOG_OUT_SUCCESS = "USER_LOG_OUT_SUCCESS";
export const USER_LOG_OUT_FAILURE = "USER_LOG_OUT_FAILURE";
export const LOGIN_USER = "LOGIN_USER"
export const USER_LOG_OUT = "USER_LOG_OUT";
export const GET_CURRENT_USER_ERROR = "GET_CURRENT_USER_ERROR";
export const CURRENT_USER_SUCCESS = "CURRENT_USER_SUCCESS";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILUR"
export const REGISTER_USER = "REGISTER_USER"

// image actions
export const GET_IMAGES = "GET_IMAGES";
export const UPLOAD_IMAGE = "UPLOAD IMAGE";
export const DELETE_IMAGE = "DELETE_IMAGE";
export const POST_COMMENT = "POST_COMMENT";

export const FETCH_IMAGES_SUCCESS = "FETCH_IMAGES_SUCCESS";
export const FETCH_IMAGES_FAILURE = "FETCH_IMAGES_FAILURE";

export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAILURE ="UPLOAD_IMAGE_FAILURE";

export const DELETE_IMAGE_SUCCESS= "DELETE_IMAGE_SUCCESS";
export const DELETE_IMAGE_FAILURE= "DELETE_IMAGE_FAILURE";

export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS"
export const POST_COMMENT_FAILURE = "POST_COMMENT_FAILURE"

export const POST_LIKE = "POST_LIKE";
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS";

